import 'rxjs';
import '@angular/animations';
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/platform-browser/animations';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';